dao.inventory.file=inventory.txt
dao.audit.file=audit.txt
dao.payments.file=payments.txt

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.elasticsearch.uris=http://localhost:9200

spring.jpa.hibernate.ddl-auto=update

jpm.client-id=${JPM_ID}
jpm.client-secret=${JPM_SECRET}
jpm.base-url=https://api-mock.payments.jpmorgan.com/api/v2
jpm.auth-url=https://id.payments.jpmorgan.com
#this is a test merchant id, later provide through env vars
jpm.merchant-id=998482157630